language: ruby
bundler_args: --without development
before_script: ./bin/ci/before_build.sh
script: "bundle exec rake spec:ci"
env:
  - CI=true
rvm:
  - 1.9.3
notifications:
  recipients:
    - gbre.111@gmail.com
branches:
  only:
    - architecture

